// <auto-generated />
using System;
using LeadManagementDashboard.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LeadManagementDashboard.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LeadManagementDashboard.Models.Lead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Company")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.ToTable("Leads");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Company = "Acme Corp",
                            CreatedAt = new DateTime(2026, 7, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            Email = "alice.johnson@example.com",
                            FirstName = "Alice",
                            LastName = "Johnson",
                            Phone = "+1-555-0101",
                            StatusId = 1
                        },
                        new
                        {
                            Id = 2,
                            Company = "Globex Ltd",
                            CreatedAt = new DateTime(2026, 7, 2, 9, 0, 0, 0, DateTimeKind.Utc),
                            Email = "bob.martinez@example.com",
                            FirstName = "Bob",
                            LastName = "Martinez",
                            Phone = "+1-555-0102",
                            StatusId = 2
                        },
                        new
                        {
                            Id = 3,
                            Company = "Initech",
                            CreatedAt = new DateTime(2026, 7, 3, 9, 0, 0, 0, DateTimeKind.Utc),
                            Email = "carla.nguyen@example.com",
                            FirstName = "Carla",
                            LastName = "Nguyen",
                            Phone = "+1-555-0103",
                            StatusId = 3
                        },
                        new
                        {
                            Id = 4,
                            Company = "Umbrella Inc",
                            CreatedAt = new DateTime(2026, 7, 4, 9, 0, 0, 0, DateTimeKind.Utc),
                            Email = "david.okafor@example.com",
                            FirstName = "David",
                            LastName = "Okafor",
                            Phone = "+1-555-0104",
                            StatusId = 4
                        },
                        new
                        {
                            Id = 5,
                            Company = "Stark Industries",
                            CreatedAt = new DateTime(2026, 7, 5, 9, 0, 0, 0, DateTimeKind.Utc),
                            Email = "elena.petrova@example.com",
                            FirstName = "Elena",
                            LastName = "Petrova",
                            Phone = "+1-555-0105",
                            StatusId = 1
                        });
                });

            modelBuilder.Entity("LeadManagementDashboard.Models.LeadActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FromStatusId")
                        .HasColumnType("int");

                    b.Property<int>("LeadId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ToStatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FromStatusId");

                    b.HasIndex("LeadId");

                    b.HasIndex("ToStatusId");

                    b.ToTable("LeadActivities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChangedAt = new DateTime(2026, 7, 2, 9, 0, 0, 0, DateTimeKind.Utc),
                            LeadId = 2,
                            Note = "Lead created",
                            ToStatusId = 1
                        },
                        new
                        {
                            Id = 2,
                            ChangedAt = new DateTime(2026, 7, 3, 9, 0, 0, 0, DateTimeKind.Utc),
                            FromStatusId = 1,
                            LeadId = 2,
                            Note = "Status changed by user",
                            ToStatusId = 2
                        },
                        new
                        {
                            Id = 3,
                            ChangedAt = new DateTime(2026, 7, 3, 9, 0, 0, 0, DateTimeKind.Utc),
                            LeadId = 3,
                            Note = "Lead created",
                            ToStatusId = 1
                        },
                        new
                        {
                            Id = 4,
                            ChangedAt = new DateTime(2026, 7, 4, 9, 0, 0, 0, DateTimeKind.Utc),
                            FromStatusId = 1,
                            LeadId = 3,
                            Note = "Status changed by user",
                            ToStatusId = 2
                        },
                        new
                        {
                            Id = 5,
                            ChangedAt = new DateTime(2026, 7, 5, 9, 0, 0, 0, DateTimeKind.Utc),
                            FromStatusId = 2,
                            LeadId = 3,
                            Note = "Status changed by user",
                            ToStatusId = 3
                        });
                });

            modelBuilder.Entity("LeadManagementDashboard.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColorCode = "#0d6efd",
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "New"
                        },
                        new
                        {
                            Id = 2,
                            ColorCode = "#ffc107",
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "Contacted"
                        },
                        new
                        {
                            Id = 3,
                            ColorCode = "#198754",
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "Qualified"
                        },
                        new
                        {
                            Id = 4,
                            ColorCode = "#6c757d",
                            DisplayOrder = 4,
                            IsActive = true,
                            Name = "Closed"
                        });
                });

            modelBuilder.Entity("LeadManagementDashboard.Models.Lead", b =>
                {
                    b.HasOne("LeadManagementDashboard.Models.Status", "Status")
                        .WithMany("Leads")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("LeadManagementDashboard.Models.LeadActivity", b =>
                {
                    b.HasOne("LeadManagementDashboard.Models.Status", "FromStatus")
                        .WithMany()
                        .HasForeignKey("FromStatusId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LeadManagementDashboard.Models.Lead", "Lead")
                        .WithMany("Activities")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeadManagementDashboard.Models.Status", "ToStatus")
                        .WithMany()
                        .HasForeignKey("ToStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromStatus");

                    b.Navigation("Lead");

                    b.Navigation("ToStatus");
                });

            modelBuilder.Entity("LeadManagementDashboard.Models.Lead", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("LeadManagementDashboard.Models.Status", b =>
                {
                    b.Navigation("Leads");
                });
#pragma warning restore 612, 618
        }
    }
}
